pipeline {
  agent {
    docker {
      image 'kiemtore27/maven-kiemtore-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }
  stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com:kiemtore27/CICD-GitHub-Jenkins-maven-sonar-docker--ArgoCD-K8s.git'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd CICD-GitHub-Jenkins-maven-sonar-docker--ArgoCD-K8s/springboot-app && mvn clean package'
      }
    }
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://192.168.41.212:9000"
      }
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd CICD-GitHub-Jenkins-maven-sonar-docker--ArgoCD-K8s/springboot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        }
      }
    }
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "kiemtore27/springb:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "CICD-GitHub-Jenkins-maven-sonar-docker--ArgoCD-K8s/springboot-app/dockerfile"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
      steps {
        script {
            sh 'cd CICD-GitHub-Jenkins-maven-sonar-docker--ArgoCD-K8s/springboot-app && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                dockerImage.push()
            }
        }
      }
    }
    stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "kiemtore27"
            GIT_USER_NAME = "kiemtore27"
        }
        steps {
            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                sh '''
                    git config user.email "kiemtore27@gmail.com"
                    git config user.name "kiemtore27"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g"CICD-GitHub-Jenkins-maven-sonar-docker--ArgoCD-K8s/springboot-app-manifests/deployment.yml
                    git add CICD-GitHub-Jenkins-maven-sonar-docker--ArgoCD-K8s/springboot-app-manifests/deployment.yml
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                '''
            }
        }
    }
  }
}

#### Set up Argo CD for continuous deployment
    #Install Argo CD on the Kubernetes cluster.
    #Define K8s cluster URL in ArgoCD UI.
    #Define the back github repo URL in ArgoCD UI. 
    #These steps will allow ArgoCD to track the changes in Backed Github repo and continuously deploy the YAML File into Kubernetes cluster in prod environment.
    
   # Configure Jenkins pipeline to integrate with Argo CD:
     #1 Add the Argo CD API token to Jenkins credentials.
     #2 Update the Jenkins pipeline to include the Argo CD deployment stage.
   # Run the Jenkins pipeline:
    # Trigger the Jenkins pipeline to start the CI/CD process for the spring-boot application.